### ISSUE TITLE
Latest report for json-schema-library

### ISSUE THREAD

**Issue by sagold** [ebdrup/json-schema-benchmark#39]
Hi ebdrup.

I am wondering why the latest report for json-schema-library failed. The report shows version 4.0.0 being used on node version 9. Cloning this repository, updating the submodule and switching to node 9 does pass all tests for json-schema-library.

Do you have any idea why this failed in your run?

Thank you for your help!
sagold

**Comment by ebdrup** [comment]
I was using node v10.16.3... 
You can see the testrun output if you click the number of failed tests in the report:
https://github.com/ebdrup/json-schema-benchmark/blob/master/reports/json-schema-library.md
This may be because I was running on an older version of the test suite. I was not going to update to latest version until the filter for including schema-validators did not filter out a lot of the fastest schema validators, like discussed in this PR: 
https://github.com/ebdrup/json-schema-benchmark/pull/37

Any help with updating the test-suite, and also updating the filter of what schema-validaters to include in the report generated would be appreciated.

**Comment by sagold** [comment]
Taking a look at your commited package-lock.json, i see that the previous version of json-schema-library was installed https://github.com/ebdrup/json-schema-benchmark/blob/master/package-lock.json#L4672. 

The merged commit from today requires the latest version, which is version 4.0.0 `npm view json-schema-library | grep latest`. 

Can you verify this?

**Comment by ebdrup** [comment]
You are right, I added a `npm run update` script to make sure to run latest versions, and re-ran the benchmark. Seems the latest version od `djv` has gotten 10x slower.

Thanks for noticing the problem.

**Comment by sagold** [comment]
Thank you for the update 🎉

**Comment by ebdrup** [comment]
Hmm, maybe the problem is the `alpha` version of `djv` used. How on earth do I specify `latest version, excluding prereleases` in semver in package.json?

**Comment by sagold** [comment]
`npm i djv@*` might do the trick. This installs version 2.1.2 instead of the latest 2.1.3-alpha.0
https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

**Comment by ebdrup** [comment]
Yes, thanks. Fixed now :-)
